### ISSUE TITLE
`tintColor` is not working on Image component

### ISSUE THREAD

**Issue by ospfranco** [microsoft/react-native-macos#1948]
### Environment

```markdown
react-native -v: 0.72.5
npm ls react-native-macos: 0.72.1
node -v: 18.15.0
npm -v:
yarn --version: 1
xcodebuild -version:
```

### Steps to reproduce the bug

1. Have an image component
2. Add tintColor as a style property.
3. Tint color should be applied

```ts
<Image
    source={Assets.checkMark}
    style={{tintColor: 'white'}}
/>
```

Here is a screenshot of Sol, where it is not being correctly applied:

![Oscar Franco Screen 000084](https://github.com/microsoft/react-native-macos/assets/1634213/a7b22a3d-b853-4983-89c9-ec2e0b3aa287)

**Comment by Saadnajmi** [comment]
Ah, I thought this was fixed 😅, I'll take a look tomorrow!

**Comment by Saadnajmi** [comment]
Just to confirm.. you see this change in your local project, if you open `RCTImageView.mm` in Xcode? If so, then it broke some new way :')

https://github.com/microsoft/react-native-macos/pull/1801/

**Comment by ospfranco** [comment]
Yes, it is there.

![Oscar Franco Screen 000091](https://github.com/microsoft/react-native-macos/assets/1634213/261dfe3a-a647-4b31-b53e-8011f6dc1413)

**Comment by Saadnajmi** [comment]
I can repro this on the main branch. So it would be present in 0.72 and 0.73 (whenever that cuts).

**Comment by ospfranco** [comment]
@saadnajmi any news about this? just updated to the latest rn-macos version (72.11) and is still broken.

**Comment by ospfranco** [comment]
This fixed on the latest versions
